USE se2019;

DROP TABLE IF EXISTS usr;
CREATE TABLE usr (
  id VARCHAR(20) NOT NULL,
  pswd VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS room;
CREATE TABLE room (
	roomId INT NOT NULL AUTO_INCREMENT,
	usrId VARCHAR(20) NOT NULL,
	temp FLOAT NOT NULL,
	settemp FLOAT NOT NULL,
	wdspd FLOAT NOT NULL,
	setwdspd FLOAT NOT NULL,
	token VARCHAR(20) NOT NULL,
	state INT NOT NULL,
	_mode INT NOT NULL,
	duration VARCHAR(20) NOT NULL,
	pwr FLOAT NOT NULL,
	cost FLOAT NOT NULL,
	PRIMARY KEY (roomId),
	FOREIGN KEY (usrId) REFERENCES usr(id)
);

DROP TABLE IF EXISTS request;
CREATE TABLE request (
);

DROP TABLE IF EXISTS billing;
CREATE TABLE billing (
);
